# This is an example configuration for shepherd.
# Instead of modifying, better make a copy and name it config.yml
# Behavior: emulate a BQ-Controller for target A, enable io-connection
mode: emulator
parameters:
  input_path: /var/shepherd/recordings/hrv.h5
  # output_path:
  # - providing a directory -> file is named emu_timestamp.h5
  # - for a complete path the filename is not changed except it exists and overwrite is disabled -> emu#num.h5
  output_path: /var/shepherd/recordings
  output_compression: 1  # should be 1 (level 1 gzip), lzf, or None (order of recommendation)
  start_time: 2022-12-13 14:15:16
  duration: 600
  virtual_source: # provide path, name (ie. default, BQ25570) or parameters
    inherit_from: BQ25570
    harvester:
      name: "mppt_bq_solar"
    V_intermediate_init_mV: 3600
    V_buck_drop_mV: 0
    V_output_mV: 3000
  force_overwrite: false
  use_cal_default: false
  enable_io: true
  io_target: A  # either Port A or B
  pwr_target: A
  aux_voltage: 3.3
    # aux_voltage options:
    # - None to disable (0 V),
    # - 0-4.5 for specific const Voltage,
    # - "mid" will output intermediate voltage (vsource storage cap),
    # - true or "main" to mirror main target voltage
  uart_baudrate: 9600  # set None to disable uart-logging for target
  skip_log_voltage: false
  skip_log_current: false
  skip_log_gpio: false
verbose: 2 # serious performance impact for value > 3
